src/process.ts
src/transformers/GovUKPayPaymentEventMessage.test.ts
src/transformers/GovUKPayPaymentEventMessage.ts

Flat message objects from the S3 stream will be formatted into GOV.UK
Pay payment events that can be consumed by Ledger. This is the first
functionality that will apply custom transforms on top the upstream
fork.

Add pay specific event format

---

src/transformers/GovUKPayPaymentEventMessage.test.ts
src/transformers/GovUKPayPaymentEventMessage.ts

Expected behaviour:
* trim inputs from individual CSV fields - these often include spaces for
readability but aren't needed in structured JSON format
* if a header is provided but the value is falsey (empty string, null)
it should not be included in the SQS message

PP-6218 Filter out empty values

---

src/consumers/SQSConsumer.ts

Logs may contain PII, this is encrypted in S3 so it cannot be leaked,
however the Splunk logs should not include these details.
This also fixes an issue where the structured logs overflow if the body
is too large.

PP-6218 Remove body details from consumer logs

---

src/transformers/GovUKPayPaymentEventMessage.test.ts
src/transformers/GovUKPayPaymentEventMessage.ts

Expected behaviour:
`id, some.value`
`100, a-value`
```
{
event_details: {
id: 100,
some: {
value: "a-value"
}
}
}
```

Allow headers to specify one level of nested attributes

---

src/transformers/GovUKPayPaymentEventMessage.test.ts
src/transformers/GovUKPayPaymentEventMessage.ts

- Currently all values in event_details are added as string. so boolean/numeric values sent to ledger doesn't match expected datatype (ex: boolean for moto/requires_3ds).
- Changed to pass values as the intended datatype.

PP-8637 Stop adding all values to event_details as string

---

Dockerfile

Update base image from alpine 3.12 to alpine 3.14
1. Deploy to test environment
2. Trigger the container to run
3. Check the logs to ensure the csv has been read and posted to SQS
I have deployed this to test, run a job through it, and [this splunk search](https://gds.splunkcloud.com/en-GB/app/gds-004-pay/payment_update_job?form.timespan.earliest=-15m&form.timespan.latest=now&form.job_id=5ab4f026) shows the job succeeding: 
None of the changes in alpine 3.13 or 3.14 should affect us other than bringing security updates:
https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.13.0
https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.14.0
3.14.1 includes fixes for apk-tools CVE-2021-36159
3.14.2 includes fixes for openssl CVE-2021-3711 and CVE-2021-3712.

PP-8916: Update base image

---

package-lock.json
package.json
src/consumers/SQSConsumer.test.ts
src/transformers/GovUKPayPaymentEventMessage.ts

This vulnerable dependency was not fixable automatically because the fix was included in eslint 8 which includes breaking changes.
Upgrades to eslint 8 including rule changes and upgrading associated plugins, which pulls in fixed version of vulnerable dependency.

PP-8953: upgrade eslint

---

.github/dependabot.yml

Update dependabot config to: 
- correctly label github actions
- monitor npm

PP-7475 dependabot configuration

---

package-lock.json
package.json

Discovered by running `npm audit fix` on master branch.

PP-9288: Bump ajv library

---

.github/workflows/post-merge.yml
.github/workflows/run-tests.yml

`npm audit` takes about 5 seconds to run so there's no issue running it every time.
I have also manually created the [alpha_release-4 tag](https://github.com/alphagov/pay-stream-s3-sqs/tree/alpha_release-4) on github as we already have a [4-release tag on AWS Test ECR](https://eu-west-1.console.aws.amazon.com/ecr/repositories/private/223851549868/govukpay/stream-s3-sqs?region=eu-west-1). The tag on ECR happened because up until now stream-s3-sqs images have been [manually pushed to ECR](https://pay-team-manual.cloudapps.digital/manual/how-to/ad-hoc-tasks.html#deploying-transaction-updater).

PP-9253: Run npm audit on each build and tag with alpha_release-XXX

---

.github/workflows/post-merge.yml
README.md

Adds concurrency to limit the post-merge workflow runs to one-at-a-time ([see pay-stubs for naming convention](https://github.com/alphagov/pay-stubs/commit/ab8ad7ca24e5d2cc4168055d8d16325d87bfb685).

PP-9376 add concurrency group to workflow

---

Dockerfile
package-lock.json

Bit of a curious one this - this `npm ci` step now seems to include `npm run prepare`. This step requires the `tsconfig.json` file to be present (previously this was copied over later). This doesn't happen on the [equivalent Toolbox Dockerfile](https://github.com/alphagov/pay-toolbox/blob/master/Dockerfile) (also node16 typescript), so not sure what's happening here, but moving the copy step seems to fix it.

PP-9434 fix Dockerfile npm ci step

---

Dockerfile

This should pick up the fix for https://nvd.nist.gov/vuln/detail/CVE-2022-28391
See dockerhub https://hub.docker.com/layers/node/library/node/16.14.2-alpine3.15/images/sha256-38bc06c682ae1f89f4c06a5f40f7a07ae438ca437a2a04cf773e66960b2d75bc?context=explore

PP-9575: Update underlying node image for stream-s3-sqs

---

README.md
src/transformers/GovUKPayPaymentEventMessage.test.ts
src/transformers/GovUKPayPaymentEventMessage.ts

Transform optional service_id and live fields a parsed CSV file to be included as a top level field on the event message sent to ledger.

PP-9873 Transform service_id and live fields

---

src/transformers/GovUKPayPaymentEventMessage.test.ts
src/transformers/GovUKPayPaymentEventMessage.ts

If a CSV column value has a value that is "true", or "false", transform
this to a boolean type when creating the event to send to ledger.

PP-9873 Transform boolean values from string

---

.vscode/settings.json
README.md
src/transformers/GovUKPayPaymentEventMessage.test.ts
src/transformers/GovUKPayPaymentEventMessage.ts

Parse upper case boolean strings - 'TRUE'/'FALSE' as booleans when transforming CSV to transaction events.

BAU Ignore case when parsing bools

---

package-lock.json
package.json

Jest includes its own coverage report so we don't need a separate coveralls command.
This is just as well, because coveralls requires the deprecated requests library, which contains a moderate security vulnerability - which is causing the security audit check to fail on all pull requests.
This PR should unblock the other dependabot PRs for this repo.

BAU: Remove unused coveralls library

---

.github/workflows/post-merge.yml

If we're only making changes to `.github` workflow files (e.g. bumping versions of actions/cache) or dependabot config, then we don't want to tag the merge as a 'release'. We follow this pattern for the app repositories (see [connector as an example](https://github.com/alphagov/pay-connector/blob/master/.github/workflows/post-merge.yml#L7)).
This should mean less work for Concourse and fewer no-op deploys for the this container.

BAU: Ignore Github config changes for post-merge workflow

---

.github/dependabot.yml

See [Github documentation for details](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates). 
This config will:
- only create security update PRs for `npm` and `github-actions` ecosystems
- create `docker` ecosystem PRs as usual (these are not always flagged as security fixes by Dependabot so these still receive 'feature' updates).

PP-10970: Dependabot config for GHA and npm security updates only

---

.github/workflows/run-tests.yml

Currently npm audit is preventing other security updates being merged, due to currently-unpatchable dev dependencies that don't affect this component.

PP-11273: Run npm audit for production dependencies only

---

.github/dependabot.yml

Ignore node version bumps from node18 until we are ready to do them.

BAU: Ignore node upgrades over version 18

---

package-lock.json

-  `npm audit fix` to update vulnerable dependencies
This is to test the updated concourse job for stream-s3-sqs which builds images in CodeBuild

PP-12037 npm audit fix

---

.github/workflows/run-tests.yml

Upgrades the following Github Actions to run on Node 20, to address deprecation warnings:
`actions/checkout`
`actions/cache`
`actions/setup-node`

PP-12244: Upgrade deprecated Github Actions

---

src/transformers/GovUKPayPaymentEventMessage.ts

Add some debug logging.
We believe that all values coming in are strings, and remain strings throughout the process, this optional debug logging (which we only enable in test) will allow us to see for sure if the numeric values are actually strings in all cases

PP-11677: Add some optional debug logging to the transformer

---

src/providers/Provider.ts
src/transformers/GovUKPayPaymentEventMessage.test.ts
src/transformers/GovUKPayPaymentEventMessage.ts

Intention is to remove any uses of the 'any' type declaration.
Important to know all data is loaded from a CSV using S3 Select with the statement `SELECT * FROM s3Object`. Without any explicit CAST statements in the S3 Select SQL all fields are strings, always! This was actually typed correctly, but then there was quite a bit of guarding against non-strings (which is impossible).
There were also tests which set values to the number `123` and a boolean data type, this is an impossible situation.
There is code which looks for 'true' and 'false' as strings and converts them to a boolean in the transformed messages for SQS. I've kept that behaviour.
I've tried to preserve the exact original effects and side effects, while rewriting the code to be more modern typescript/javascript, and also …

Pp 11677: Resolve usage of any type declarations
